version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    ports:
      - "127.0.0.1:9300:9300"
      - "127.0.0.1:9200:9200"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=password
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
